// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDpKATTCciZ7XQPegeOK6cDm0Gc2bVWJO0',
    appId: '1:872315562624:web:4f268ee1d10bd551f65465',
    messagingSenderId: '872315562624',
    projectId: 'nexgen-78cd0',
    authDomain: 'nexgen-78cd0.firebaseapp.com',
    storageBucket: 'nexgen-78cd0.appspot.com',
    measurementId: 'G-820CSD3XF1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAOOTFq6ebwX-p8OvNc73KtfuR3hCeq8TU',
    appId: '1:872315562624:android:a10ac1f2b50523d5f65465',
    messagingSenderId: '872315562624',
    projectId: 'nexgen-78cd0',
    storageBucket: 'nexgen-78cd0.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCBkb-JqrAkzKqQdLLhE18TI2tI69JeZfM',
    appId: '1:872315562624:ios:4a844a70c487cdc3f65465',
    messagingSenderId: '872315562624',
    projectId: 'nexgen-78cd0',
    storageBucket: 'nexgen-78cd0.appspot.com',
    iosBundleId: 'com.example.nexgen',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCBkb-JqrAkzKqQdLLhE18TI2tI69JeZfM',
    appId: '1:872315562624:ios:4a844a70c487cdc3f65465',
    messagingSenderId: '872315562624',
    projectId: 'nexgen-78cd0',
    storageBucket: 'nexgen-78cd0.appspot.com',
    iosBundleId: 'com.example.nexgen',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDpKATTCciZ7XQPegeOK6cDm0Gc2bVWJO0',
    appId: '1:872315562624:web:20f74d11e3d0ddd7f65465',
    messagingSenderId: '872315562624',
    projectId: 'nexgen-78cd0',
    authDomain: 'nexgen-78cd0.firebaseapp.com',
    storageBucket: 'nexgen-78cd0.appspot.com',
    measurementId: 'G-EZJ4G8KX3N',
  );
}
